### PR TITLE
184 update save btn ux

### LINKED ISSUE #184: Change Save button text to Saved when it is clicked.
@lmorchard @pdehaan 
When I click on copy button it is changed from `copy` to `copied`. Which gave an excellent user experience. But when I click on `Save` button nothing happens. After clicking on save button, themes got saved down the page. So, for a new user, it takes some time to realize what is actually happening. I think it would be better if we change the save button text from `save` to `saved`, once it is clicked. 

Before clicking `Copy` button-
themerissue1
After clicking `Copy` button-
themerissue2

But in case of `Save` button-
Before clicking-
themerissue3

After clicking-
themerissue4

Thanks!

### PR DESCRIPTION
**Pull request by HandsomeMedia**
Fixes #184
- initial state shows disabled button with "Save" text
- edited state shows enabled button with "Save" text
- saved state shows disabled button with "Saved!" text

### CODE REVIEW

**Comment by lmorchard** [comment]
Works for me!

**Comment by HandsomeMedia** [comment]
Hah! Well I'm astounded there are no issues with best practice, given my novice React skills...  @lmorchard 
 - If you have a moment, could you or another maintainer give it a once over - surely I done goofed somewhere?

**Comment by lmorchard** [comment]
> Hah! Well I'm astounded there are no issues with best practice, given my novice React skills

It all looks pretty straightforward and clean to me! I was trying to think of a simpler way to determine if the last-saved theme had changed, rather than keeping a copy around in UI state. But, I couldn't think of anything better so 🤷‍♂️ :shipit:

**Comment by HandsomeMedia** [comment]
I will pat myself on the back then.  Thanks!

**Pull request merged**
