### PR TITLE
I850 fixes error were used imgs are deleted when max storage is reached

### LINKED ISSUE #850: Images used in saved/set themes are wrongly deleted when going over the maximum limit
**[Affected versions]:**
- Firefox Nightly 71.0a1, Build ID: 20191013213650
- Firefox Beta 70.0b14, Build ID:20191013213650
- Firefox Release 69.0.3, Build ID: 20191009172106

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox Color add-on zip modified in order to link to the [stage](https://color.stage.mozaws.net/) website.
- Have the previous Firefox Color add-on installed through about:debugging.
- Have saved themes with images until the “You have almost reached your storage limit! You may need to delete some images or themes to make space”.

**[Steps to reproduce]:**
1. Open the profile from the prerequisites.
2. Navigate to the https://color.stage.mozaws.net/ website.
3. Click the “Custom backgrounds” section.
4. Add an image with a higher size in order to go over the maximum limit.
5. Navigate to the “Saved themes” section and observe the section.

**[Expected result]:**
- All images are deleted from the saved themes.

**[Actual result]:**
- The saved themes are correctly displayed with the added images.

**[Notes]:**
- After overreaching the maximum local storage size all previously added images are deleted from the local storage. Depending on the size of the last image added it might be added or not to the local storage.
- Attached a screen recording with the issue [here](https://drive.google.com/open?id=1_VDAX17Tve3zrtLW1lJ90DfsXliIbUQo).

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #850 

I removed this snippet in #839 so this is just reverting that...

### CODE REVIEW

**Comment by caitmuenster** [comment]
I think this fixes the issue. [Link to screen recording of test](https://drive.google.com/open?id=15i0MHHesV_iy7aV0oA_ObITU7BHpkA2Z). 

@Softvision-AndreeaCupsa, is this what you expected?

**Comment by Softvision-AndreeaCupsa** [comment]
@caitmuenster ,
From what I can see in this in video, the maximum local storage limit is not exceeded. Are the images deleted from the local storage and saved themes after exceeding it?
The [issue](https://github.com/mozilla/FirefoxColor/issues/850) I filled is that after exceeding the maximum limit all images are deleted, from local storage and saved themes.

**Comment by caitmuenster** [comment]
Thanks @Softvision-AndreeaCupsa! This was as close as I was able to get to the storage limit; I was prevented from exceeding the storage limit and was not able to reproduce your error.

**Comment by caitmuenster** [comment]
Just replicated @Softvision-AndreeaCupsa's issue. 

What if we disable "Random" when local.storage is detected to be full? We want to drive them to clear images/themes on their own

TBH I don't think a lot of users are going to run into this issue. If this doesn't take too long to fix, we can tackle this now; otherwise I don't consider this to be a blocker to the next release.

**Comment by rebmullin** [comment]
hmm, is this how you reproduced this issue - via clicking the "Random" button?

I am not sure disabling "Random" will fix this, b/c you will still be able to click this button if local storage isn't full - even if it's close to capacity - which I am assuming it is when you ran into this issue...?

**Comment by rebmullin** [comment]
hey @caitmuenster/@Softvision-AndreeaCupsa!, I've made an update. Can you please check this branch again when you get a chance? thanks:)

**Comment by caitmuenster** [comment]
This looked good to me -- I hit the maximum limit, clicked "Random," and no images were deleted from my saved themes. 

2019 11 04 Color - PR 855 2019-11-04 15_15_25

**Pull request merged**
