### PR TITLE
fix: mark advanced colors that are gone in Proton

### LINKED ISSUE #969: Updates to themeable properties with Firefox 89
We should update Firefox Color to reflect changes coming to themes for Firefox 89 (release date: June 1, 2021): 

* `tab_background_separator` will no longer be supported
* `toolbar_field_separator` will no longer be supported

We'll need to remove those properties from the Advanced Colors section of Firefox Color.

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes #969

### CODE REVIEW

**Comment by caitmuenster** [comment]
@Rob--W, I wasn't clear from my local test where this is should show up (if it supposed to show up in the UI at all). Could you give a quick overview of how this change is applied?

**Comment by Rob--W** [comment]
The "Advanced colors" tab should show this.

**Comment by caitmuenster** [comment]
I see it! 
Screen Shot 2021-04-28 at 2 00 14 PM

I'm not sure it would be understandable to non-technical theme artists, though. How would you feel about putting an asterisk by the name of the property instead and have the X link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors? We should have an update coming in soon that will mark `tab_background_separator` and `toolbar_field_separator` as unsupported in 89+.

**Comment by Rob--W** [comment]
> I'm not sure it would be understandable to non-technical theme artists, though. How would you feel about putting an asterisk by the name of the property instead

I tried to choose a suffix that was short enough to not overflow the field. An asterisk would be sufficiently small too, but not very obvious as readers would have to figure out where the asterisk is explained. I can turn it into a "deprecated" icon that explains what happens in a tooltip.

> and have the X link to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors?

That link already exists in the side panel.

> We should have an update coming in soon that will mark `tab_background_separator` and `toolbar_field_separator` as unsupported in 89+.

MDN currently shows an image that explains the role of all (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme/themes_components_annotations.png (permalink to [source on Github](https://github.com/mdn/content/blob/3e5d8947cf03d1ae758aff8926c04c38eca2db2a/files/en-us/mozilla/add-ons/webextensions/manifest.json/theme/themes_components_annotations.png))). I hope that both are kept, so that it may be easier for theme devs to migrate. Possibly by taking the existing image and highlighting the balloons of the color names (e.g. by background/border color).

**Pull request closed without merging**
