### PR TITLE
wip: implementation of import feature

### PR DESCRIPTION
**Pull request by himanshujaidka**
need a review on the logic that reads JSON file from zip file, so that I will continue, issue #943  @Rob--W

### CODE REVIEW

**Review by Rob--W — CHANGES_REQUESTED** [review]
There is no zip reading going on here. I have previously linked to some relevant documentation in #943. Please read my comments carefully and try to apply what you learn from my comments and external documentation.

This PR in its current form is at best an experiment at file reading. It does not implement any logic that is uniquely specific and necessary for resolving #943.

There are a few unrelated commits in this pull request. If you can, try to rebase your branch so that unrelated commits don't appear in the pull request.

**Comment by himanshujaidka** [comment]
> There is no zip reading going on here. I have previously linked to some relevant documentation in #943. Please read my comments carefully and try to apply what you learn from my comments and external documentation.
> 
> This PR in its current form is at best an experiment at file reading. It does not implement any logic that is uniquely specific and necessary for resolving #943.
> 
> There are a few unrelated commits in this pull request. If you can, try to rebase your branch so that unrelated commits don't appear in the pull request.

okay

**Comment by himanshujaidka** [comment]
> There is no zip reading going on here. I have previously linked to some relevant documentation in #943. Please read my comments carefully and try to apply what you learn from my comments and external documentation.
> 
> This PR in its current form is at best an experiment at file reading. It does not implement any logic that is uniquely specific and necessary for resolving #943.
> 
> There are a few unrelated commits in this pull request. If you can, try to rebase your branch so that unrelated commits don't appear in the pull request.

@Rob--W used git rebase and removed unrelated commits

**Review by Rob--W — CHANGES_REQUESTED** [review]
This patch is heading in the wrong direction. Please try to understand the task (#943) before working on any implementation at all AND run/test your program, before asking for a review of your code.

It seems that the task that you're working on is beyond your current abilities. I am guessing so, because despite multiple pointers here and in chat, you've pushed a patch here that doesn't do anything that comes closer to a fix for #943. It's a combination of copy-pasting code snippets (e.g. from [multer](https://github.com/expressjs/multer#diskstorage)) without understanding what they're doing and when/how they should be used. You're also using Node.js standard libraries (and external libraries designed for Node.js), while the feature is meant to run in a web page, on the user's browser only. Node.js-specific code could be used to ease the testing of the logic, but the primary logic should be independent of Node.js.

I suggest to re-evaluate whether this is a task that you want to work on, or whether you want to practice simpler tasks (maybe in other projects?) first.

**Comment by himanshujaidka** [comment]
Yeah, I have used libraries but to be honest I have not copied the code, the time I guess around 7-8 months ago when I picked this issue, on that time I was learning web development but today I have successfully completed the course and now trying to implement what I learnt so far, I tried so many times to implement import feature and your advice of practising simpler tasks is seems to be healthy, so I will follow up that advice first, hope in future I will be solve this but now pls train me to that level of solving

**Comment by himanshujaidka** [comment]
I will be happy if you will share some simpler tasks

**Pull request closed without merging**
